using AudioCodec.Enum;
using System.Runtime.InteropServices;

namespace AudioCodec.Types;

[StructLayout(LayoutKind.Sequential)]
public unsafe struct AVFormatContext {
    public AVClass* Class;
    public AVInputFormat* InputFormat;
    public AVOutputFormat* OutputFormat;
    public void* PrivateData;
    public AVIOContext* PB;
    public int CTX_Flags;
    public uint NBStream;
    public AVStream** Streams;
    public uint NBStreamGroups;
    public AVStreamGroup** StreamGroups;
    public uint NBChapters;
    public AVChapter** Chapters;
    public byte* Url;
    public long StartTime;
    public long Duration;
    public long BitRate;
    public uint PacketSize;
    public int MaxDelay;
    public int Flags;
    public long ProbeSize;
    public long MaxAnalyzeDuration;
    public byte* Key;
    public int KeyLen;
    public uint NBPrograms;
    public AVProgram** Programs;
    public AVCodecID VideoCodecId;
    public AVCodecID AudioCodecId;
    public AVCodecID SubtitleCodecId;
    public AVCodecID DataCodecId;
    public AVDictionary* Metadata;
    public long StartTimeRealTime;
    public int FPSProbeSize;
    public int ErrorRecognition;
    public AVIOInterruptCB InterruptCallback;
    public int Debug;
    public int MaxStreams;
    public uint MaxIndexSize;
    public uint MaxPictureBuffer;
    public long MaxInterleaveDelta;
    public int MaxTSProbe;
    public int MaxChunkDuration;
    public int MaxChunkSize;
    public int MaxProbePackets;
    public int StrictSTDCompilance;
    public int EventFlags;
    public int AvoidNegativeTS;
    public int AudioPreload;
    public int UseWallclockAsTimeStamps;
    public int SkipEstimateDurationFromPTS;
    public int AVIOFlags;
    public AVDurationEstimationMethod DurationEstimationMethod;
    public long SkipInitialBytes;
    public uint CorrectTsOverflow;
    public int SeekToAny;
    public int FlushPackets;
    public int ProbeScore;
    public int FormatProbeSize;
    public byte* CodecWhitelist;
    public byte* FormatWhitelist;
    public byte* ProtocolWhitelist;
    public byte* ProtocolBlacklist;
    public int IORepositioned;
    public AVCodec* VideoCodec;
    public AVCodec* AudioCodec;
    public AVCodec* SubtitleCodec;
    public AVCodec* DataCodec;
    public int MetadataHeaderPadding;
    public void* Opaque;
    public IntPtr ControlMessageCB;
    public long OutputTSOffset;
    public byte* DumpSeparator;
    public IntPtr IOOpen;
    public IntPtr IOClose2;
    public long DurationProbeSize;
    public byte* Name;
}
