<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android</TargetFrameworks>
		<TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('linux'))">$(TargetFrameworks);net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>

		<SingleProject>true</SingleProject>
		<UseMaui>false</UseMaui>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>

		<Optimize Condition="'$(Configuration)' == 'Release'">true</Optimize>

		<Authors>Azurshi</Authors>
		<Version Condition="'$(Configuration)' == 'Debug'">0.0.6-dev</Version>
		<Version Condition="'$(Configuration)' == 'Release'">0.0.1</Version>
		<Description> v0.0: Codec for decode audio.</Description>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="AudioDecoder.Convert.cs">
	    <DependentUpon>AudioDecoder.cs</DependentUpon>
	  </None>
	  <None Include="AudioDecoder.Decode.cs">
	    <DependentUpon>AudioDecoder.cs</DependentUpon>
	  </None>
	  <None Include="AudioDecoder.DecodeLoop.cs">
	    <DependentUpon>AudioDecoder.cs</DependentUpon>
	  </None>
	  <None Include="AudioDecoder.Receive.cs">
	    <DependentUpon>AudioDecoder.cs</DependentUpon>
	  </None>
	  <None Include="AudioDecoder.Seek.cs">
	    <DependentUpon>AudioDecoder.cs</DependentUpon>
	  </None>
	  <None Include="AudioDecoder.Types.cs">
	    <DependentUpon>AudioDecoder.cs</DependentUpon>
	  </None>
	  <None Include="AudioDecoder.WorkerLoop.cs">
	    <DependentUpon>AudioDecoder.cs</DependentUpon>
	  </None>
	</ItemGroup>

</Project>
